"""Build the synthetic dataset the SHOWCASE media is captured from.

SHOWCASE.md promises that every figure in it comes from a synthetic dataset and
that no real project names appear. Until now that promise rested on a corpus
somebody generated by hand and never committed, so nothing in the showcase could
be reproduced or checked — and the first time a figure was quoted from a real
machine instead, nothing caught it.

This script is that corpus, written down. Fixed seed, fixed timestamps, so the
same numbers come out on any machine:

    python scripts/make_showcase_data.py --out .showcase-data
    contextrot water --data-dir .showcase-data --days 0

Three fake projects, two agents, three models, and a deliberate shape: Opus
degrades with context fill while Sonnet stays flat on the same work, cache reads
dominate the token totals the way they do in real agent sessions, and the
failure signals are placed per fill bucket rather than by a modulus, so no
aliasing manufactures a threshold that isn't there.

Writes nothing outside ``--out``. Nothing here touches a real transcript.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path

# A fixed start date keeps timestamps — and therefore the --days windows the
# showcase quotes — identical between runs.
START = datetime(2026, 8, 1, 9, 0, tzinfo=timezone.utc)

# project slug -> (sessions, model, turns per session)
PROJECTS = (
    ("auth-service", "claude-opus-5", 26, 14),
    ("web-dashboard", "claude-sonnet-5", 18, 11),
    ("cli-tools", "claude-haiku-4-5", 12, 8),
)

# Failure rate per fill decile, for the agent that degrades. Flat for the others.
ROTTING = (0.03, 0.03, 0.04, 0.04, 0.05, 0.06, 0.09, 0.13, 0.17, 0.19)
FLAT = (0.05,) * 10

TOOLS = ("Read", "Edit", "Bash", "Grep", "Write")
FILES = ("auth/session.py", "auth/tokens.py", "api/routes.py", "db/models.py", "util/log.py")


def _usage(prompt: int, output: int, fresh: int = 0) -> dict:
    """Claude Code's usage object, split the way a long session really splits.

    Almost all of a prompt is a cache read by the second step of a turn, which is
    why water and cost totals are dominated by replay rather than by output.
    """
    fresh = min(fresh or 0, prompt)
    return {
        "input_tokens": 24,
        "cache_creation_input_tokens": fresh,
        "cache_read_input_tokens": max(0, prompt - fresh - 24),
        "output_tokens": output,
    }


def _claude_session(
    rng: random.Random, project: str, model: str, index: int, turns: int, rates: tuple
) -> list[dict]:
    """One Claude Code transcript as a list of JSONL entries."""
    window = 1_000_000 if "opus" in model or "sonnet-5" in model else 200_000
    cwd = f"/home/dev/{project}"
    started = START + timedelta(days=index % 21, hours=index % 7, minutes=index * 3)
    lines: list[dict] = []
    uid = 0
    prompt = 18_000  # startup overhead: system prompt, tool schemas, instructions

    # Place failures per fill bucket rather than by a modulus over step number:
    # a modulus correlates with the fill sweep and manufactures a knee.
    for turn in range(turns):
        uid += 1
        ts = (started + timedelta(minutes=turn * 4)).isoformat().replace("+00:00", "Z")
        lines.append(
            {
                "parentUuid": None if turn == 0 else f"a{uid - 1}",
                "isSidechain": False,
                "type": "user",
                "message": {"role": "user", "content": f"task {turn}: tidy {rng.choice(FILES)}"},
                "timestamp": ts,
                "uuid": f"u{uid}",
                "cwd": cwd,
                "sessionId": f"demo-{project}-{index}",
            }
        )

        for step in range(rng.randint(3, 6)):
            uid += 1
            fill = min(0.99, prompt / window)
            bucket = min(9, int(fill * 10))
            failed = rng.random() < rates[bucket]
            tool = rng.choice(TOOLS)
            target = f"{cwd}/{rng.choice(FILES)}"
            ts = (
                (started + timedelta(minutes=turn * 4, seconds=step * 25 + 5))
                .isoformat()
                .replace("+00:00", "Z")
            )
            output = rng.randint(180, 900)
            fresh = rng.randint(1_200, 4_500) if step == 0 else 0
            lines.append(
                {
                    "parentUuid": f"u{uid - 1}",
                    "isSidechain": False,
                    "type": "assistant",
                    "message": {
                        "role": "assistant",
                        "model": model,
                        "content": [
                            {"type": "text", "text": "Working on it."},
                            {
                                "type": "tool_use",
                                "id": f"t{uid}",
                                "name": tool,
                                "input": {"file_path": target},
                            },
                        ],
                        "usage": _usage(prompt, output, fresh),
                    },
                    "timestamp": ts,
                    "uuid": f"a{uid}",
                    "cwd": cwd,
                    "sessionId": f"demo-{project}-{index}",
                }
            )
            lines.append(
                {
                    "parentUuid": f"a{uid}",
                    "isSidechain": False,
                    "type": "user",
                    "message": {
                        "role": "user",
                        "content": [
                            {
                                "type": "tool_result",
                                "tool_use_id": f"t{uid}",
                                "is_error": failed,
                                "content": (
                                    "String to replace not found in file."
                                    if failed
                                    else "ok\n" * 3
                                ),
                            }
                        ],
                    },
                    "timestamp": ts,
                    "uuid": f"r{uid}",
                    "cwd": cwd,
                    "sessionId": f"demo-{project}-{index}",
                }
            )
            # The whole prompt is replayed next step, plus the tool result.
            prompt += output + rng.randint(2_500, 9_000)
            if prompt > window * 0.99:
                prompt = int(window * 0.35)  # a compaction
    return lines


def _codex_session(rng: random.Random, index: int, turns: int) -> list[dict]:
    """One Codex CLI rollout, so the agent comparison has a second agent."""
    lines: list[dict] = []
    started = START + timedelta(days=index % 14, hours=3, minutes=index * 7)
    total_in = 9_000
    # The model lives in turn_context, not in the token_count info — that is where
    # the adapter reads it from, and without it every step is "unknown".
    lines.append(
        {
            "type": "turn_context",
            "timestamp": started.isoformat().replace("+00:00", "Z"),
            "payload": {"model": "gpt-5.4-codex", "cwd": "/home/dev/cli-tools"},
        }
    )
    for turn in range(turns):
        for step in range(rng.randint(2, 4)):
            ts = (
                (started + timedelta(minutes=turn * 5, seconds=step * 20))
                .isoformat()
                .replace("+00:00", "Z")
            )
            output = rng.randint(150, 700)
            lines.append(
                {
                    "type": "event_msg",
                    "timestamp": ts,
                    "payload": {
                        "type": "token_count",
                        "info": {
                            "model": "gpt-5.4-codex",
                            "model_context_window": 272_000,
                            "last_token_usage": {
                                "input_tokens": total_in,
                                # Codex reports the cached prefix inside input_tokens.
                                "cached_input_tokens": max(0, total_in - 2_400),
                                "output_tokens": output,
                            },
                        },
                    },
                }
            )
            total_in += output + rng.randint(1_800, 6_000)
            if total_in > 260_000:
                total_in = 60_000
    return lines


def build(out: Path) -> dict:
    """Write the corpus. Returns a small summary for the caller to print."""
    if out.exists():
        shutil.rmtree(out)
    # Both adapters read the same --data-dir, so the layout has to satisfy both
    # without either one picking up the other's files. Claude Code globs
    # "*/*.jsonl" from the root; Codex rglobs "rollout-*.jsonl", so putting the
    # rollouts two levels down keeps them out of Claude's glob.
    claude_root = out
    codex_root = out / "codex" / "sessions"
    claude_root.mkdir(parents=True, exist_ok=True)
    codex_root.mkdir(parents=True)

    rng = random.Random(20260801)
    sessions = 0
    for project, model, count, turns in PROJECTS:
        rates = ROTTING if "opus" in model else FLAT
        d = claude_root / f"-home-dev-{project}"
        d.mkdir(parents=True, exist_ok=True)
        for index in range(count):
            lines = _claude_session(rng, project, model, index, turns, rates)
            path = d / f"demo-{project}-{index:03d}.jsonl"
            path.write_text(
                "".join(json.dumps(line) + "\n" for line in lines), encoding="utf-8"
            )
            sessions += 1

    for index in range(9):
        lines = _codex_session(rng, index, 9)
        path = codex_root / f"rollout-demo-{index:03d}.jsonl"
        path.write_text("".join(json.dumps(line) + "\n" for line in lines), encoding="utf-8")
        sessions += 1

    return {"sessions": sessions, "out": str(out)}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(".showcase-data"),
        help="Directory to write the synthetic corpus into (recreated each run).",
    )
    args = ap.parse_args()
    summary = build(args.out)
    print(f"wrote {summary['sessions']} synthetic sessions to {summary['out']}")
    print("capture with: contextrot water --data-dir", summary["out"], "--days 0")


if __name__ == "__main__":
    main()
